name: Publish

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: git config --global user.email "furkanyildiz58.fy@gmail.com"
      - run: git config --global user.name "furkanyildizz"
      - run: npm cache clean --force
      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2
      - run: npm version ${{ steps.version.outputs.version-without-v }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
